###############################################################################
# CS/CNS 171 Fall 2015
#
# This is a template Makefile for the assignment. Edit it however you find
# convenient.
###############################################################################
CC = g++
FLAGS = -g
SOURCES = pt1.cpp

EXENAME = pt1

all: $(SOURCES)
	$(CC) $(FLAGS) $(SOURCES) -o $(EXENAME) 

clean:
	rm -f *.o $(EXENAME)

.PHONY: all clean
